CREATE TABLE profesor (
	codprofesor serial4 NOT NULL,
	nombre varchar(255) NOT NULL,
	CONSTRAINT profesor_pkey PRIMARY KEY (codprofesor)
);

INSERT INTO profesor (nombre) VALUES
	 ('CAMPANA AÑASCO, RILDO'),
	 ('AYALA FALCON, ELOY ELADIO'),
	 ('SANCHEZ HUARINGA, CARLOS'),
	 ('QUINTEROS CHAVEZ, SILVIO'),
	 ('MIRANDA TORRES, CESAR AURELIO'),
	 ('MONDRAGÓN HERNÁNDEZ, MARGARITA DELICIA'),
	 ('PALACIOS SAMANIEGO, LEONCIO GABRIEL'),
	 ('ROMERO AQUINO, JUAN CARLOS'),
	 ('VALDIVIA MENDOZA, HECTOR GIOVANNY'),
	 ('PEÑA YALICO, VICENTE');
INSERT INTO profesor (nombre) VALUES
	 ('CAÑOTE FAJARDO, PERCY VICTOR'),
	 ('SAN BARTOLOME MONTERO, JAIME'),
	 ('MOSQUERA MOLINA, MIGUEL ANGEL'),
	 ('SALCEDO TORRES, JOAQUIN MAGNOT'),
	 ('COSSA CABANILLAS, JESUS ALBERTO'),
	 ('TORRE CAMONES, ANIVAL ALFREDO'),
	 ('HUAROTE ZEGARRA, RAUL EDUARDO'),
	 ('NAVARRO NEYRA, MIGUEL ANGEL'),
	 ('CHUNG CHING, RICARDO ALEJANDRO'),
	 ('VASQUEZ DOMINGUEZ, RIQUELMER APOLINARIO');
INSERT INTO profesor (nombre) VALUES
	 ('HUAMAN SANCHEZ, ALEJANDRO APOLINARIO'),
	 ('BERMEO CARRASCO, OSMAR ARNALDO'),
	 ('CERNADES GOMEZ, JESÚS'),
	 ('HUANCA SULLCA, VICTOR'),
	 ('ARAMBULO OSTOS, CARLOS EDUARDO'),
	 ('CUTIPA COAQUIRA, MIGUEL'),
	 ('BRONCANO TORRES, JUAN CARLOS'),
	 ('KALA BÉJAR, LOURDES CRISTINA'),
	 ('SINCHE CHOCCA, NILDO'),
	 ('ALCANTARA MALCA, DANIEL ADOLFO');
INSERT INTO profesor (nombre) VALUES
	 ('REYES ACOSTA, ROSARIO'),
	 ('FUKUDA KAGAMI, NANCY ELENA'),
	 ('RONDINEL PINEDA, PETRA ELINE'),
	 ('VALENZUELA GONZALEZ, ERIK OMAR'),
	 ('OSORIO MARUJO, BILMA ELIZABETH'),
	 ('CHAFLOQUE ELIAS, CARLOS ALBERTO'),
	 ('GOMEZ GALVEZ, SUSANA TERESA'),
	 ('CHAVARRI ARCE, RAQUEL MARTHA'),
	 ('ACEVEDO RAYMUNDO, SAUL'),
	 ('CUROTTO CORNEJO, MARIA MERCEDES');
INSERT INTO profesor (nombre) VALUES
	 ('HUERTA ORTEGA, JAVIER ARMANDO'),
	 ('LEÓN ZÁRATE, ANA MERCEDES'),
	 ('BONIFACIO CASTRO, ALEXANDER ABEL'),
	 ('ACOSTA DE LA CRUZ, PEDRO RAUL'),
	 ('MONCADA CAJAVILCA, VICTOR JOSÉ'),
	 ('ECHEANDIA CESPEDES, JAVIER FRANCISCO'),
	 ('LESCANO AVILA, LUIS ALBERTO'),
	 ('BENITES YARLEQUÉ, JOSÉ VALERIO'),
	 ('TOCTO INGA, PAUL MILLER'),
	 ('ALVARADO RODRÍGUEZ, JOSÉ LUIS');
INSERT INTO profesor (nombre) VALUES
	 ('HERRERA VEGA, HECTOR ALEXIS'),
	 ('SEGURA GARCÍA, YOLANDA ADRIANA'),
	 ('CERNA VALDEZ, YARKO ALVARO'),
	 ('HUALLPA GUTIERREZ, WALTER ANTONIO'),
	 ('ZEGARRA BORRERO, ANTONIO'),
	 ('SOTOMAYOR ARAMBURU, FERNANDO FORTUNATO'),
	 ('OSTOS CORDERO, BENITO LEONARDO'),
	 ('CUEVA HUANUCO, EDDIE DANNY'),
	 ('EGÚZQUIZA FIGUEROA, MARÍA ENERINA'),
	 ('CAICEDO BUSTAMANTE, VICTOR ANTONIO');
INSERT INTO profesor (nombre) VALUES
	 ('VALDIVIA CAMACHO, GLORIA ESTHER'),
	 ('LAU CARRILLO, CARMEN IVONNE'),
	 ('ROJAS MENDOZA, DORIS FANNY'),
	 ('LLANCCE MONDRAGON, LUISA'),
	 ('HUAMANI HUAMANI, GLORIA TERESITA'),
	 ('VILLANUEVA HERRERA, JOSÉ ALBERTO'),
	 ('MORILLO ROJAS, DANIEL'),
	 ('PUCCIO QUEVEDO, BRUNO JUAN'),
	 ('OLIVERA PAYANO, RICARDO'),
	 ('LEYTON DIAZ, VICTOR ADOLFO');
INSERT INTO profesor (nombre) VALUES
	 ('PONCE SÁNCHEZ, CARLOS FIDEL'),
	 ('RIZABAL FLORES, ELIANA CECILIA'),
	 ('REVILLA LOAYZA, REYNA ROSARIO'),
	 ('FALCONI VASQUEZ, RODOLFO ELÍAS'),
	 ('TORRES CORTEZ, JULIO LORENZO'),
	 ('DELZO ESTEBAN, CESAR ENRIQUE'),
	 ('ORIA CHAVARRIA, WILLIAM'),
	 ('VALLE SANTOS, JOHN CLERK'),
	 ('ZAMORA YANSI, RICHARD ISMAEL'),
	 ('ESPINOZA ESPINOZA, JOSE ALFREDO');
INSERT INTO profesor (nombre) VALUES
	 ('CHAPARRO MINAYA, ENRIQUE VLADIMIR'),
	 ('CALIZAYA NEYRA, PERCY ANGEL'),
	 ('ZARATE OTAROLA, LEONIDAS BENITO'),
	 ('BRAVO QUISPE, ALDO ANTONIO'),
	 ('FLORES CISNEROS, ERNESTO ROBINSON'),
	 ('LINARES VALENCIA, JOSE ANTONIO'),
	 ('TRIGO PÉREZ, CARLOS ALFREDO'),
	 ('LEYVA EUSEBIO, JOSÉ ALBERTO'),
	 ('ZAMORA MONTERO, WALTER FERNANDO'),
	 ('HIROMOTO HIROMOTO, FELIPE TSUTOMU');
INSERT INTO profesor (nombre) VALUES
	 ('GOMEZ ESPINOZA, LUISA VIVIANA'),
	 ('FISFALEN HUERTA, MARIO HEINRICH'),
	 ('KRAJNIK STULIN, FRANCO LUCIANO'),
	 ('UN JAN LIAU HING, EMILIO ALBERTO'),
	 ('ARADIEL CASTAÑEDA, HILARIO'),
	 ('CANCHANO CARO, JAVIER TOLENTINO'),
	 ('GUZMAN YANGATO, JORGE FERNANDO'),
	 ('ARTEAGA CORTEZ, HUMBERTO URBANO'),
	 ('AUDANTE RAMOS, NESTOR RAFAEL'),
	 ('RAMOS MORENO, JAIME IGNACIO');
INSERT INTO profesor (nombre) VALUES
	 ('LLANOS PANDURO, JORGE DANIEL'),
	 ('MELGAREJO SOLIS, RONALD ALFONSO'),
	 ('MORALES CUELLAR, MERY NOEMI'),
	 ('LUJÁN CAMPOS, LUIS ALBERTO'),
	 ('CANELO SOTELO, CÉSAR ALDO'),
	 ('SANCHEZ ESPINOZA, JAVIER CONCEPCIÓN'),
	 ('OPORTO DIAZ, SAMUEL ALONSO'),
	 ('BORJA ROSALES, RUBÉN ARTURO'),
	 ('NEYRA LUZA, ALBERTO CARLOS'),
	 ('OCROSPOMA PELLA, MARIA PATRICIA');
INSERT INTO profesor (nombre) VALUES
	 ('SALAS CORDERO, ROCIO GUADALUPE'),
	 ('RODRÍGUEZ ULLOA, RICARDO AURELIO'),
	 ('ANTAURCO TRUJILLO, JESÚS WALTER'),
	 ('SOTELO VILLENA, JUAN CARLOS'),
	 ('RAMOS MATÍAS, PEDRO MELITÓN'),
	 ('AYALA LIMAYLLA, CHRISTIAN SAEL'),
	 ('LÓPEZ VILLANUEVA, PABLO EDWIN'),
	 ('RODRIGUEZ RAFAEL, GLEN DARIO'),
	 ('CORONEL CASTILLO, ERIC GUSTAVO'),
	 ('CORDOVA NERI, TEODORO LUCIANO');
INSERT INTO profesor (nombre) VALUES
	 ('SALAS COZ, ERWIN ERASMO'),
	 ('REYNA MONTEVERDE, TINO EDUARDO'),
	 ('MEDINA AQUINO, LUIS FELIPE'),
	 ('ULFE VEGA, LUIS ALBERTO'),
	 ('HUARCAYA JUNES, ALEJANDRINA NELLY'),
	 ('MOLINA ESTACIO, NINOSKA'),
	 ('TALAVERANO GARCÍA, JULIO CESAR'),
	 ('CABALLERO ORTIZ, JOSE ALBERTO'),
	 ('MÉNDEZ VALDIVIA, CELEDONIO'),
	 ('ALIAGA VILCHEZ, TOBIAS ENRIQUE');
INSERT INTO profesor (nombre) VALUES
	 ('MORI LEON, NILTON CESAR'),
	 ('ZULOAGA ROTTA, LUIS ALBERTO'),
	 ('VALENZUELA POSADAS, JORGE MARTIN'),
	 ('ESPINOZA FALCON, LUIS ALBERTO'),
	 ('ESPINAL LAU, MIGUEL EDUARDO'),
	 ('JANJACHI TORIBIO, CARLOS ALBERTO'),
	 ('RAMOS MONTES, CARLOS NELSON'),
	 ('VELARDE CARPIO, MANUEL HELARF'),
	 ('BRINGAS MASGO, ISAAC ERNESTO'),
	 ('HUAPAYA CIRIACO, ALBERTO JESUS');
INSERT INTO profesor (nombre) VALUES
	 ('LEIVA POVIS, JORGE ZENON'),
	 ('CALLATA GARRIDO, MARLENE'),
	 ('SOTELO ANTAURCO, SANTOS CIRIACO'),
	 ('MANSILLA LOPEZ, JUAN PABLO JESUS'),
	 ('CISNEROS NAPRAVNIK, YAN EDUARDO'),
	 ('RAMOS MUÑOZ, ALFREDO MARINO'),
	 ('CALLO MOSCOSO, LUIS ALBERTO'),
	 ('VILCAPOMA ESCURRA, EDGAR SOCRATES'),
	 ('PARRA OSORIO, HERNAN JULIO'),
	 ('POMA GARCIA, JOSE ANTONIO');
INSERT INTO profesor (nombre) VALUES
	 ('GARCIA CORZO, JUAN CARLOS'),
	 ('MUÑOZ INGA, CARLOS'),
	 ('CIEZA DE LEÓN TUESTA, EDUARDO JOSÉ'),
	 ('TARAZONA PONTE, SANTIAGO'),
	 ('CRUZ FIGUEROA, GUILLERMO ROLDAN'),
	 ('AGUERO MAURICIO, ALFREDO ROLANDO'),
	 ('ZARATE FLORES, MARCEL'),
	 ('ZUÑIGA MERCADO, ANTONIO'),
	 ('ACUÑA PINAUD, LEONCIO LUIS'),
	 ('ALANIA VERA, ENRIQUE GUSTAVO');
INSERT INTO profesor (nombre) VALUES
	 ('ANCO BONIFAZ, HERLINDA IRMA'),
	 ('ARTICA CUYUBAMBA, GUSTAVO'),
	 ('BARRIENTOS RODRIGUEZ, VICTOR RAUL'),
	 ('CALDERON ZAVALETA, SANDY LUZ'),
	 ('CANALES BERNAL, ALDO DARIO'),
	 ('CARDENAS ADVINCULA, YSRAEL ALBERTO'),
	 ('CARRANZA BARRENA, WILFREDO EDUARDO'),
	 ('CARRANZA MILLA, EMERSON FLORMIRO'),
	 ('CARREÑO FERNANDEZ, HANS'),
	 ('CONTRERAS SILVA, CARLOS ENRIQUE');
INSERT INTO profesor (nombre) VALUES
	 ('COSSIO CAMPEAN, JUNIOR BRYAN'),
	 ('CRUZ YUPANQUI, GLADYS'),
	 ('ENERO ANTONIO, JAIME ALFREDO'),
	 ('FERNANDEZ AGUILAR, LUIS ALBERTO'),
	 ('FERNANDEZ LOSTAUNAU, CÉSAR ANTONIO'),
	 ('FLORES BASHI, CARLOS ANTONIO'),
	 ('FLORES GALLO, DIANA CAROLINA'),
	 ('FLORES SOLIS, FERNANDO ROLY'),
	 ('FUENTES MAGUIÑA, JUAN LUIS JAISUÑO'),
	 ('GARCIA LA RIVA, JOSE CARLOS');
INSERT INTO profesor (nombre) VALUES
	 ('GARCIA RAMOS, CINTYA'),
	 ('GAVIDIA CALDERON, CARLOS GABRIEL'),
	 ('HUAMAN URETA, PEÑAFORT LUIS'),
	 ('HUYHUA PAUCAR, HARLIN PAUL'),
	 ('JARAMILLO SALDAÑA, FERNANDO AMADEO'),
	 ('MATIAS HERRERA, CHRISTIAN ALBERTO'),
	 ('MONTES ESKENAZY, EDWIN JORGE'),
	 ('MURILLO LUNA, MANUEL ANTONIO'),
	 ('MUÑOZ MARTINEZ, YURI BERNARDO'),
	 ('NAVARRO QUIÑONES, EDINSON ROBERTO');
INSERT INTO profesor (nombre) VALUES
	 ('OLIDEN MARTINEZ, JOSÉ FORTUNATO'),
	 ('ORDOÑEZ ROJAS, GERARDO MANUEL'),
	 ('RAMOS PALOMINO, EDGAR'),
	 ('RIOS VARILLAS, ROSARIO CIRILA'),
	 ('ROMERO CIEZA, JOSE'),
	 ('ROSALES REYES, GANIMEDES TRIMEGISTRO'),
	 ('SANCHEZ TORRES, HEIDI ISABEL'),
	 ('SIMICH LÓPEZ, VICTOR ARTURO'),
	 ('TAIPE ARIAS, JOHN EDISON'),
	 ('VALENZUELA DE LA CRUZ, BASILIO');
INSERT INTO profesor (nombre) VALUES
	 ('VENTO GARCIA, OSCAR ARTURO'),
	 ('VERA RONCALLA, CESAR ANIBAL'),
	 ('VILCA HUAMAN, ARTURO'),
	 ('YALICO BUSTILLOS, KAREN MARGARITA'),
	 ('ZALDÍVAR ALVAREZ, OSCAR GUILLERMO'),
	 ('ZORILLA VARGAS, CARLOS');
