CREATE TABLE Curso (
    Codigo VARCHAR(10) PRIMARY KEY,
    Nombre VARCHAR(255) NOT NULL
);

INSERT INTO curso (codigo,nombre) VALUES
	 ('BEF01','ETICA Y FILOSOFIA POLITICA'),
	 ('BEG01','ECONOMIA GENERAL'),
	 ('BFI01','FISICA I'),
	 ('BIC01','INTRODUCCION A LA COMPUTACION'),
	 ('BMA01','CALCULO DIFERENCIAL'),
	 ('BMA02','CALCULO INTEGRAL'),
	 ('BMA03','ALGEBRA LINEAL'),
	 ('BQU01','QUIMICA I'),
	 ('BRC01','REDACCION Y COMUNICACION'),
	 ('BRN01','REALIDAD NACIONAL, CONSTITUCION Y DERECHOS HUMANOS');
INSERT INTO curso (codigo,nombre) VALUES
	 ('FB101','GEOMETRIA ANALITICA'),
	 ('FB202','QUIMICA II'),
	 ('FB301','MATEMATICA DISCRETA'),
	 ('FB303','CALCULO MULTIVARIABLE'),
	 ('FB305','ESTADISTICA Y PROBABILIDADES'),
	 ('FB401','FISICA II'),
	 ('FB402','CALCULO NUMERICO'),
	 ('FB403','ECUACIONES DIFERENCIALES'),
	 ('FB405','ESTADISTICA APLICADA'),
	 ('FB501','MATEMATICA APLICADA');
INSERT INTO curso (codigo,nombre) VALUES
	 ('GE003','TALLER DE PROYECTO DE INVESTIGACION'),
	 ('GE004','TALLER DE INVESTIGACION'),
	 ('GE101','INTRODUCCION A LA INGENIERIA INDUSTRIAL'),
	 ('GE112','TEORIA DE JUEGOS Y LA NEGOCIACION'),
	 ('GE113','TALLER DE CONSULTORIA DE EMPRESAS'),
	 ('GE122','SISTEMA DE COSTOS'),
	 ('GE124','COMERCIO INTERNACIONAL'),
	 ('GE128','DIAGNOSTICO DE EMPRESAS'),
	 ('GE501','TEORIA ORGANIZACIONAL'),
	 ('GE502','INGENIERIA DEL TRABAJO I');
INSERT INTO curso (codigo,nombre) VALUES
	 ('GE602','CONTABILIDAD FINANCIERA'),
	 ('GE603','INGENIERIA DEL TRABAJO II'),
	 ('GE604','ADMINISTRACION Y ORGANIZACION'),
	 ('GE605','SISTEMA Y GESTION FINANCIERA'),
	 ('GE701','LOGISTICA EMPRESARIAL'),
	 ('GE702','INGENIERIA ECONOMICA'),
	 ('GE703','SISTEMAS INTEGRADOS EMPRESARIALES'),
	 ('GE704','CONTABILIDAD DE COSTOS Y PRESUPUESTOS'),
	 ('GE709','SISTEMAS DE CALIDAD'),
	 ('GE801','PLANEAMIENTO Y GESTION ESTRATEGICA');
INSERT INTO curso (codigo,nombre) VALUES
	 ('GE802','GESTION DE LA CADENA DE SUMINISTRO'),
	 ('GE803','SISTEMAS ANALITICOS'),
	 ('GE805','MERCADOTECNIA'),
	 ('GE901','INNOVACION Y EMPRENDIMIENTO DE NEGOCIOS'),
	 ('GE902','DISEÑO Y EVALUACION DE PROYECTOS'),
	 ('GE903','GESTION DEL TALENTO HUMANO'),
	 ('GE905','PLANEAMIENTO Y CONTROL DE OPERACIONES'),
	 ('GE906','GESTION FINANCIERA'),
	 ('GP514','COMERCIO INTERNACIONAL'),
	 ('GP525','DISEÑO Y EVALUACION DE PROYECTOS');
INSERT INTO curso (codigo,nombre) VALUES
	 ('GP545','PROYECTO DE TESIS EN INGENIERIA INDUSTRIAL II'),
	 ('GP575','DIAGNOSTICO EMPRESARIAL'),
	 ('HS144','COMPORTAMIENTO ORGANIZACIONAL'),
	 ('HU102','DESARROLLO PERSONAL'),
	 ('HU111','LEGISLACION EMPRESARIAL Y TRIBUTARIA'),
	 ('HU112','COMPORTAMIENTO ORGANIZACIONAL'),
	 ('HU201','SOCIOLOGIA'),
	 ('HU301','METODOLOGIA DE LA INVESTIGACION'),
	 ('SI036','TALLER DE INVESTIGACION'),
	 ('SI055','GESTION DE PROYECTOS');
INSERT INTO curso (codigo,nombre) VALUES
	 ('SI075','AUDITORIA DE SISTEMAS'),
	 ('SI077','INTELIGENCIA ARTIFICIAL'),
	 ('SI085','APLICACION DE NEGOCIOS ELECTRONICOS'),
	 ('SI095','INGENIERIA EMPRESARIAL'),
	 ('SI101','INTRODUCCION AL PENSAMIENTO Y A LA INGENIERIA  DE SISTEMAS'),
	 ('SI111','TEORIA DE DECISIONES'),
	 ('SI114','BASE DE DATOS'),
	 ('SI130','GESTION DE LA INFORMACION'),
	 ('SI150','ANALITICA DE DATOS'),
	 ('SI155','CIBERSEGURIDAD');
INSERT INTO curso (codigo,nombre) VALUES
	 ('SI201','PSICOLOGIA SISTEMICA'),
	 ('SI203','TEORIA Y CIENCIA DE SISTEMAS'),
	 ('SI204','TEORIA GENERAL DE SISTEMAS'),
	 ('SI205','ALGORITMIA Y ESTRUCTURA DE DATOS'),
	 ('SI207','SISTEMAS BIOLOGICOS Y ECOLOGICOS'),
	 ('SI301','TEORIA Y CIENCIA DE SISTEMAS APLICADA'),
	 ('SI302','PROGRAMACION ORIENTADA A OBJETOS'),
	 ('SI401','LENGUAJE DE PROGRAMACION'),
	 ('SI403','METODOLOGIA DE LOS SISTEMAS BLANDOS'),
	 ('SI405','MODELADO CONCEPTUAL DE DATOS');
INSERT INTO curso (codigo,nombre) VALUES
	 ('SI501','INVESTIGACION DE OPERACIONES I'),
	 ('SI503','INGENIERIA DE PROCESOS'),
	 ('SI505','DISEÑO DE BASE DE DATOS'),
	 ('SI601','INVESTIGACION DE OPERACIONES II'),
	 ('SI602','DINAMICA DE SISTEMAS'),
	 ('SI603','MODELADO DE PROCESOS DE CICLO DE VIDA DE SISTEMAS'),
	 ('SI604','ANALISIS Y DISEÑO DE SISTEMAS'),
	 ('SI605','ARQUITECTURA EMPRESARIAL'),
	 ('SI607','ARQUITECTURA COMPUTACIONAL Y REDES'),
	 ('SI701','MODELADO SISTEMICO Y SIMULACION');
INSERT INTO curso (codigo,nombre) VALUES
	 ('SI702','TALLER DE DINAMICA DE SISTEMAS'),
	 ('SI704','GESTION DE LA INGENIERIA DE SISTEMAS'),
	 ('SI705','ESTANDARES DE LA INGENIERIA DE SISTEMAS'),
	 ('SI707','INGENIERIA DE SOFTWARE'),
	 ('SI801','MODELO DEL SISTEMA VIABLE'),
	 ('SI805','INTEGRACION DE SISTEMAS'),
	 ('SI806','DESARROLLO ADAPTATIVO E INTEGRADO DEL SW'),
	 ('SI807','SISTEMAS DE INTELIGENCIA DE NEGOCIO'),
	 ('SI902','INGENIERIA DE SISTEMAS DE SERVICIO'),
	 ('SI903','IMPLEMENTACION DE SISTEMAS');
INSERT INTO curso (codigo,nombre) VALUES
	 ('SI904','SEGURIDAD DE SISTEMAS'),
	 ('SI905','TALLER DE PROYECTO DE INVESTIGACION'),
	 ('ST114','TEORIA DE DECISIONES'),
	 ('ST124','SIMULACION'),
	 ('ST150','ANALITICA DE DATOS'),
	 ('ST224','SISTEMAS ECONOMICOS'),
	 ('ST236','PROYECTO DE TESIS EN INGENIERIA DE SISTEMAS II'),
	 ('ST275','AUDITORIA DE SISTEMAS'),
	 ('ST285','APLICACION DE NEGOCIOS ELECTRONICOS'),
	 ('ST295','INGENIERIA EMPRESARIAL');
INSERT INTO curso (codigo,nombre) VALUES
	 ('ST702','TALLER DINAMICA DE SISTEMAS'),
	 ('SW101','INTRODUCCION A LA INGENIERIA DE SOFTWARE'),
	 ('SW301','ARQUITECTURA DE COMPUTADORAS I'),
	 ('SW303','LENGUAJES DE PROGRAMACION I (IMPERATIVO)'),
	 ('SW305','ALGORITMIA Y ESTRUCTURA DE DATOS AVANZADA'),
	 ('SW401','ANALISIS Y MODELAMIENTO DE DATOS'),
	 ('SW403','LENGUAJE DE PROGRAMACION II (ORIENTADA A OBJETOS)'),
	 ('SW405','INGENIERIA DE REQUERIMIENTOS I'),
	 ('SW407','SISTEMAS OPERATIVOS'),
	 ('TE101','DIBUJO DE INGENIERIA');
INSERT INTO curso (codigo,nombre) VALUES
	 ('TE111','INNOVACION Y GESTION TECNOLOGICA'),
	 ('TE121','ERGONOMIA'),
	 ('TE122','PROCESOS AGROINDUSTRIALES'),
	 ('TE124','GESTION DE LA ENERGIA'),
	 ('TE126','GESTION DEL MANTENIMIENTO'),
	 ('TE205','DIBUJO Y GEOMETRIA DESCRIPTIVA'),
	 ('TE301','FISICO QUIMICA Y OPERACIONES UNITARIAS'),
	 ('TE302','DISEÑO ASISTIDO POR COMPUTADOR'),
	 ('TE401','TERMODINAMICA'),
	 ('TE501','ELECTRICIDAD Y ELECTRONICA INDUSTRIAL');
INSERT INTO curso (codigo,nombre) VALUES
	 ('TE503','PROCESOS INDUSTRIALES I'),
	 ('TE601','INGENIERIA DE MATERIALES'),
	 ('TE602','PROCESOS INDUSTRIALES II'),
	 ('TE603','CONTROL ESTADISTICO DE PROCESOS'),
	 ('TE604','MAQUINARIA E INSTRUMENTACION INDUSTRIAL'),
	 ('TE701','ANALISIS DE PROCESOS DE MANUFACTURA'),
	 ('TE801','AUTOMATIZACION Y CONTROL DE PROCESOS'),
	 ('TE802','INGENIERIA DEL PRODUCTO'),
	 ('TE803','SISTEMAS INTEGRADOS DE CALIDAD'),
	 ('TE901','SEGURIDAD Y SALUD OCUPACIONAL');
INSERT INTO curso (codigo,nombre) VALUES
	 ('TP314','INGENIERIA DEL PRODUCTO'),
	 ('GE001','PROYECTO DE TESIS EN INGENIERIA INDUSTRIAL II'),
	 ('GE904','PROYECTO DE TESIS EN INGENIERIA INDUSTRIAL I'),
	 ('GE121','DISEÑO Y DISPOSICION DE PLANTAS'),
	 ('GP114','TEORIA DE PRECIOS'),
	 ('GP134','MODELOS DE GESTION EMPRESARIAL'),
	 ('GP205','GESTION DE MANTENIMIENTO'),
	 ('GP234','ANALISIS ECONOMICO EN INGENIERIA'),
	 ('GP235','GESTION FINANCIERA'),
	 ('GP515','PLANEAMIENTO Y DIRECCION ESTRATEGICA');
INSERT INTO curso (codigo,nombre) VALUES
	 ('GP535','PROYECTO DE TESIS EN INGENIERIA INDUSTRIAL I'),
	 ('HS204','LEGISLACION EMPRESARIAL'),
	 ('HU400','PRACTICAS PREPROFESIONALES II'),
	 ('SI035','PROYECTO DE TESIS EN INGENIERIA SISTEMAS II'),
	 ('SI901','PROYECTO DE TESIS EN INGENIERIA  SISTEMAS I'),
	 ('ST205','TOPICOS DE INGENIERIA DE SISTEMAS'),
	 ('ST215','SEGURIDAD INFORMATICA'),
	 ('ST235','PROYECTO DE TESIS EN INGENIERIA DE SISTEMAS I'),
	 ('ST274','BASE DE DATOS'),
	 ('TP254','AUTOMATIZACION Y CONTROL DE PROCESOS');
INSERT INTO curso (codigo,nombre) VALUES
	 ('TP505','GESTION Y ASEGURAMIENTO DE CALIDAD TOTAL'),
	 ('XP200','PRACTICAS PREPROFESIONALES II'),
	 ('GP154','ADMINISTRACION DE RECURSOS HUMANOS'),
	 ('GP244','SISTEMAS DE COSTOS'),
	 ('GP324','GESTION LOGISTICA Y DE OPERACIONES'),
	 ('GP404','PLANEAMIENTO Y CONTROL DE LA PRODUCCION'),
	 ('MA195','METODOS NUMERICOS'),
	 ('PA754','PROYECTO DE INVESTIGACION EN INGENIERIA DE SISTEMAS'),
	 ('PA761','TOPICOS ESPECIALES EN INGENIERIA DE SISTEMAS II'),
	 ('PA770','TEORIA DE CONTROL EN SISTEMAS PRODUCTIVOS');
INSERT INTO curso (codigo,nombre) VALUES
	 ('ST214','ADMINISTRACION DE BASE DE DATOS'),
	 ('ST255','GESTION DE PROYECTOS INFORMATICOS'),
	 ('ST334','SISTEMAS DE COMUNICACION DE DATOS'),
	 ('ST414','INTELIGENCIA ARTIFICIAL'),
	 ('TP324','ERGONOMIA'),
	 ('GP123','ADMINISTRACION Y ORGANIZACION'),
	 ('GP314','MERCADOTECNIA'),
	 ('GP555','GESTION DE NEGOCIOS I'),
	 ('HS405','TOPICOS DE NEGOCIACION'),
	 ('SI119','TALLER DE DISEÑO DE SISTEMAS INTELIGENTES');
INSERT INTO curso (codigo,nombre) VALUES
	 ('ST155','CIBERSEGURIDAD'),
	 ('ST314','ARQUITECTURA DEL COMPUTADOR'),
	 ('ST324','SISTEMAS OPERATIVOS'),
	 ('TE127','ROBOTICA INDUSTRIAL'),
	 ('TP103','ELECTRICIDAD Y ELECTRONICA INDUSTRIAL'),
	 ('TP123','SISTEMAS DIGITALES'),
	 ('GE115','DESARROLLO ECONOMICO'),
	 ('GP304','LOGISTICA EMPRESARIAL'),
	 ('GP403','SISTEMAS PRODUCTIVOS'),
	 ('PA163','PROBLEMAS DE TECNOLOGIA INDUSTRIAL');
INSERT INTO curso (codigo,nombre) VALUES
	 ('ST123','INVESTIGACION DE OPERACIONES II'),
	 ('ST222','LENGUAJES DE PROGRAMACION'),
	 ('ST231','TALLER DE HERRAMIENTAS SOFTWARE I'),
	 ('ST254','ADMINISTRACION DE LA CALIDAD DE SOFTWARE'),
	 ('ST605','ARQUITECTURA EMPRESARIAL'),
	 ('TE125','LEAN MANUFACTURING'),
	 ('TP404','HIGIENE Y SEGURIDAD INDUSTRIAL'),
	 ('CB313','FISICA MODERNA'),
	 ('GP245','FINANCIAMIENTO CORPORATIVO'),
	 ('GP585','TOPICOS DE INGENIERIA INDUSTRIAL');
INSERT INTO curso (codigo,nombre) VALUES
	 ('ST253','TECNICAS DE DOCUMENTACION Y ARCHIVOS'),
	 ('TP224','PROCESOS INDUSTRIALES II'),
	 ('TP313','DISEÑO GRAFICO');
